version: '3.8'

services:
  bot:
    build: .
    container_name: amirgroup_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    network_mode: "host"
