"""add_debt_fields_to_recon_log

Revision ID: 4d1430d8c063
Revises: add_verification_group_fields
Create Date: 2026-04-21 23:21:36.490113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1430d8c063'
down_revision: Union[str, None] = 'add_verification_group_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_logs', sa.Column('total_debt', sa.BigInteger(), nullable=True))
    op.add_column('reconciliation_logs', sa.Column('overdue_debt', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_logs', 'overdue_debt')
    op.drop_column('reconciliation_logs', 'total_debt')
    # ### end Alembic commands ###
