"""Initial tables

Revision ID: 4f9840814bd0
Revises: 
Create Date: 2026-04-21 10:50:33.516386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9840814bd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_ids', sa.Text(), nullable=True),
    sa.Column('reply_markup', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configs_id'), 'configs', ['id'], unique=False)
    op.create_index(op.f('ix_configs_key'), 'configs', ['key'], unique=True)
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'failed', 'cancelled', 'completed', name='reconstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_id'), 'reconciliations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_uuid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('market_name', sa.String(), nullable=True),
    sa.Column('passport_front_side', sa.String(), nullable=True),
    sa.Column('passport_back_side', sa.String(), nullable=True),
    sa.Column('pinfl', sa.String(length=14), nullable=True),
    sa.Column('selfie_photo', sa.String(), nullable=True),
    sa.Column('verification_status', sa.Enum('new', 'verification_pending', 'verified', 'rejected', name='verificationstatus'), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'blocked', name='userstatus'), nullable=True),
    sa.Column('role', sa.Enum('user', 'auditor', 'admin', name='userrole'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('broadcast_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=True),
    sa.Column('tele_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('sent', 'failed', name='broadcastlogstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tele_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_logs_id'), 'broadcast_logs', ['id'], unique=False)
    op.create_table('reconciliation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=True),
    sa.Column('tele_user_id', sa.Integer(), nullable=True),
    sa.Column('disown_text', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('sent', 'failed', 'confirmed', 'disowned', name='reconlogstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tele_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_logs_id'), 'reconciliation_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_logs_id'), table_name='reconciliation_logs')
    op.drop_table('reconciliation_logs')
    op.drop_index(op.f('ix_broadcast_logs_id'), table_name='broadcast_logs')
    op.drop_table('broadcast_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reconciliations_id'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_configs_key'), table_name='configs')
    op.drop_index(op.f('ix_configs_id'), table_name='configs')
    op.drop_table('configs')
    op.drop_index(op.f('ix_broadcasts_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
