"""add_region_to_user

Revision ID: cfd2d4dd10d9
Revises: 4d1430d8c063
Create Date: 2026-04-28 23:42:00.858031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd2d4dd10d9'
down_revision: Union[str, None] = '4d1430d8c063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'region')
    # ### end Alembic commands ###
